export const TODO_CREATION_REQUEST="TODO_CREATION_REQUEST"
export const TODO_CREATION_SUCCESS="TODO_CREATION_SUCCESS"
export const TODO_CREATION_FAIL="TODO_CREATION_FAIL"


export const TODO_DISPLAY_REQUEST="TODO_DISPLAY_REQUEST"
export const TODO_DISPLAY_SUCCESS="TODO_DISPLAY_SUCCESS"
export const TODO_DISPLAY_FAIL="TODO_DISPLAY_FAIL"